name: Build and Test

on: 
  pull_request: 
    branches: [ main ]

jobs: 
  build-and-test: 
    name: Build Test Lint
    runs-on: ubuntu-latest  # Virtual machine environment  

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test --if-present

  security-scan:
    name: Security Scan  
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run npm audit
        #fails if the build has high vulnerabilities
        run: npm audit --audit-level=high

#add in database CI/CD when db is setup